<?php
$pageTitle = 'Beranda';
$activeMenu = 'home';
$deskripsi = $profil['deskripsi'] ?? $pengaturan['deskripsi'] ?? 'Organisasi siswa pecinta alam yang belajar memimpin, menjaga lingkungan, dan bertualang secara bertanggung jawab.';
$visi = $profil['visi'] ?? 'Menjadi ruang tumbuh bagi pelajar yang peduli alam dan berkarakter.';
$misi = $profil['misi'] ?? 'Belajar bersama, berkegiatan dengan aman, dan memberi dampak baik untuk lingkungan.';
ob_start();
?>
<section class="atlas-hero">
    <div class="hero-contour">

    </div><div class="container position-relative">
        <div class="row align-items-center min-vh-75 gy-5">
            <div class="col-lg-7"><p class="hero-route"><span></span> Titik awal perjalanan Anda</p><h1>Belajar membaca alam.<br><em>Berani menempuh</em> arah baru.</h1><p class="hero-copy"><?= htmlspecialchars($deskripsi) ?></p><div class="hero-actions"><a href="<?= BASE_URL ?>/pendaftaran" class="btn-route">Mulai pendaftaran <i class="bi bi-arrow-up-right"></i></a><a href="<?= BASE_URL ?>/profil" class="btn-text">Kenali organisasi <i class="bi bi-arrow-right"></i></a></div></div><div class="col-lg-5"><div class="expedition-card"><div class="expedition-card-top"><span>RUTE / 01</span><i class="bi bi-crosshair"></i></div><h2>Jalur menuju anggota SISPALA</h2><ol class="route-list"><li><span>01</span><div><strong>Kenali organisasi</strong><small>Pelajari nilai, kegiatan, dan arah kami.</small></div></li><li><span>02</span><div><strong>Isi formulir</strong><small>Sampaikan data dan motivasi Anda.</small></div></li><li><span>03</span><div><strong>Mulai perjalanan</strong><small>Ikuti informasi seleksi dari pengurus.</small></div></li></ol></div></div></div></div></section>
<section class="route-stats"><div class="container"><div class="row g-0"><div class="col-md-4"><div class="stat-route"><i class="bi bi-people"></i><strong><?= $jumlahAnggota ?>+</strong><span>Anggota terdata</span></div></div><div class="col-md-4"><div class="stat-route"><i class="bi bi-camera"></i><strong><?= count($galeri) ?>+</strong><span>Dokumentasi pilihan</span></div></div><div class="col-md-4"><div class="stat-route"><i class="bi bi-journal-text"></i><strong><?= count($berita) ?>+</strong><span>Informasi terbaru</span></div></div></div></div></section>
<section class="atlas-section intro-section"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><div class="map-panel"><span class="map-coord">SISPALA / ID</span><i class="bi bi-compass-fill"></i><div class="map-line line-one"></div><div class="map-line line-two"></div><span class="map-pin pin-one"></span><span class="map-pin pin-two"></span></div></div><div class="col-lg-6 offset-lg-1"><h2>Menemukan arah bersama, bukan sekadar sampai tujuan.</h2><p class="lead-copy"><?= htmlspecialchars($visi) ?></p><p><?= nl2br(htmlspecialchars($misi)) ?></p><a href="<?= BASE_URL ?>/profil" class="inline-link">Lihat profil organisasi <i class="bi bi-arrow-right"></i></a></div></div></div></section>
<section class="atlas-section activity-section"><div class="container"><div class="section-heading"><div><span class="section-kicker">Kegiatan</span><h2>Setiap langkah adalah latihan.</h2></div><p>Ruang belajar yang membentuk kepekaan, ketangguhan, dan kerja sama.</p></div><div class="activity-track"><article><span class="activity-icon"><i class="bi bi-tree"></i></span><h3>Eksplorasi alam</h3><p>Mengamati, memahami, dan menghargai lingkungan sekitar.</p></article><article><span class="activity-icon"><i class="bi bi-shield-check"></i></span><h3>Latihan kesiapsiagaan</h3><p>Melatih tanggung jawab, keselamatan, serta kemampuan dasar lapangan.</p></article><article><span class="activity-icon"><i class="bi bi-people"></i></span><h3>Aksi bersama</h3><p>Membangun kepemimpinan melalui kolaborasi dan kepedulian sosial.</p></article></div></div></section>
<section class="atlas-section gallery-preview"><div class="container"><div class="section-heading"><div><span class="section-kicker">Jejak kegiatan</span><h2>Catatan perjalanan kami.</h2></div><a href="<?= BASE_URL ?>/galeri" class="inline-link">Buka galeri <i class="bi bi-arrow-right"></i></a></div><?php if (!empty($galeri)): ?><div class="photo-grid"><?php foreach ($galeri as $index => $item): $foto = $item['foto'] ?? ''; ?><a href="<?= BASE_URL ?>/galeri" class="photo-tile tile-<?= $index % 6 ?>"><?php if ($foto): ?><img src="<?= BASE_URL ?>/uploads/gallery/<?= htmlspecialchars($foto) ?>" alt="<?= htmlspecialchars($item['judul'] ?? 'Dokumentasi kegiatan') ?>" loading="lazy"><?php else: ?><span class="photo-placeholder"><i class="bi bi-image"></i></span><?php endif; ?><span><?= htmlspecialchars($item['judul'] ?? 'Dokumentasi kegiatan') ?></span></a><?php endforeach; ?></div><?php else: ?><div class="empty-route"><i class="bi bi-images"></i><p>Dokumentasi kegiatan akan segera ditampilkan di sini.</p></div><?php endif; ?></div></section>
<section class="atlas-section news-section"><div class="container"><div class="section-heading"><div><span class="section-kicker">Dari basecamp</span><h2>Berita terbaru.</h2></div><a href="<?= BASE_URL ?>/berita" class="inline-link">Semua berita <i class="bi bi-arrow-right"></i></a></div><div class="news-route-list"><?php if (!empty($berita)): foreach ($berita as $item): $slug = $item['slug'] ?? $item['id']; ?><a href="<?= BASE_URL ?>/berita/<?= urlencode($slug) ?>" class="news-route"><span class="news-date"><?= htmlspecialchars($item['tanggal'] ?? $item['created_at'] ?? 'Info') ?></span><h3><?= htmlspecialchars($item['judul']) ?></h3><i class="bi bi-arrow-up-right"></i></a><?php endforeach; else: ?><div class="empty-route"><i class="bi bi-newspaper"></i><p>Berita terbaru belum tersedia.</p></div><?php endif; ?></div></div></section>
<section class="join-banner"><div class="container"><div><span class="section-kicker">Langkah berikutnya</span><h2>Siap menjadikan rasa ingin tahu sebagai perjalanan?</h2></div><a href="<?= BASE_URL ?>/pendaftaran" class="btn-light-route">Daftar sebagai calon anggota <i class="bi bi-arrow-up-right"></i></a></div></section>
<?php
$content = ob_get_clean();
require ROOT_PATH . '/app/Views/layouts/public_layout.php';
